### ISSUE TITLE
Make sure all links are resolved in documentation. 

### ISSUE THREAD

**Issue by Carreau** [napari/docs#47] opened 2022-10-06 12:43 UTC
## 📚 Documentation

While looking into 5183, I realized that if there is a non-resolved link, ther string `class="xref myst"` will appear in the html. We should likely update the docs build to make sure it fails if this value is found.

It currently appears in two places in the dev docs:

```
$ rg 'class="xref myst"'  dev
dev/plugins/best_practices.html
639:and <span class="xref myst"><code class="docutils literal notranslate"><span class="pre">get_stylesheet</span></code></span> ...
639:... <span class="xref myst"><code class="docutils literal notranslate"><span class="pre">napari.qt</span></code></span> module.</p>
```

**Comment by Czaki** [comment] 2022-11-08 07:13
This is partial duplicate of [#2274](https://github.com/napari/docs/issues/439)

**Comment by melissawm** [comment] 2024-08-09 12:55
No such links appear anymore, so closing.

**Closed as completed by melissawm** 2024-08-09 12:55 UTC
Labels: documentation
